### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by wikeeyang** [CanvaChen/VidGen#1]
大佬，我看了一下，您只改了 scripts 目录下的 sample_t2v.py 和 sample_t2v.sh 两个脚本吧？
我用您的脚本替换 scripts 目录下原来的脚本，跑了还是报错，如下：

(hpcaienv) tkadmin@ubu:~/hpcai/VidGen$ bash scripts/sample_t2v.sh
making attention of type 'causual_spatial_temporal' with 512 in_channels
making attention of type 'causual_spatial_temporal' with 512 in_channels
vae load from ./pretrain_model/vidgen/vae/vae_pytorch_model.bin
_IncompatibleKeys(missing_keys=[], unexpected_keys=['loss.logvar', 'loss.perceptual_loss.scaling_layer.shift', 'loss.perceptual_loss.scaling_layer.scale', 'loss.perceptual_loss.net.slice1.0.weight', 'loss.perceptual_loss.net.slice1.0.bias', 'loss.perceptual_loss.net.slice1.2.weight', 'loss.perceptual_loss.net.slice1.2.bias', 'loss.perceptual_loss.net.slice2.5.weight', 'loss.perceptual_loss.net.slice2.5.bias', 'loss.perceptual_loss.net.slice2.7.weight', 'loss.perceptual_loss.net.slice2.7.bias', 'loss.perceptual_loss.net.slice3.10.weight', 'loss.perceptual_loss.net.slice3.10.bias', 'loss.perceptual_loss.net.slice3.12.weight', 'loss.perceptual_loss.net.slice3.12.bias', 'loss.perceptual_loss.net.slice3.14.weight', 'loss.perceptual_loss.net.slice3.14.bias', 'loss.perceptual_loss.net.slice4.17.weight', 'loss.perceptual_loss.net.slice4.17.bias', 'loss.perceptual_loss.net.slice4.19.weight', 'loss.perceptual_loss.net.slice4.19.bias', 'loss.perceptual_loss.net.slice4.21.weight', 'loss.perceptual_loss.net.slice4.21.bias', 'loss.perceptual_loss.net.slice5.24.weight', 'loss.perceptual_loss.net.slice5.24.bias', 'loss.perceptual_loss.net.slice5.26.weight', 'loss.perceptual_loss.net.slice5.26.bias', 'loss.perceptual_loss.net.slice5.28.weight', 'loss.perceptual_loss.net.slice5.28.bias', 'loss.perceptual_loss.lin0.model.1.weight', 'loss.perceptual_loss.lin1.model.1.weight', 'loss.perceptual_loss.lin2.model.1.weight', 'loss.perceptual_loss.lin3.model.1.weight', 'loss.perceptual_loss.lin4.model.1.weight'])
./pretrain_model/vidgen/text_encoder/t5-v1_1-xxl
Loading checkpoint shards: 100%|█████████████████████████████| 2/2 [00:04<00:00,  2.24s/it]
model load from: ./pretrain_model/vidgen/transformer/diffusion_pytorch_model.bin
<All keys matched successfully>
Traceback (most recent call last):
  File "/home/tkadmin/hpcai/VidGen/scripts/sample_t2v.py", line 298, in <module>
    text_cond_encode = text_encoder.encode([prompt])
  File "/home/tkadmin/hpcai/VidGen/core/models/text_encoder/t5.py", line 351, in encode
    caption_embs, emb_masks = self.t5.get_text_embeddings(text)
  File "/home/tkadmin/hpcai/VidGen/core/models/text_encoder/t5.py", line 162, in get_text_embeddings
    text_encoder_embs = self.model(
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1980, in forward
    encoder_outputs = self.encoder(
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1115, in forward
    layer_outputs = layer_module(
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 695, in forward
    self_attention_outputs = self.layer[0](
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 602, in forward
    attention_output = self.SelfAttention(
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 521, in forward
    query_states = shape(self.q(hidden_states))  # (batch_size, n_heads, seq_length, dim_per_head)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/tkadmin/miniconda3/envs/hpcaienv/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

两块显卡分开加载是没问题，占用显存空间我看也差不多，如下：

|   0  NVIDIA GeForce RTX 4090        Off | 00000000:0B:00.0 Off |                  Off |
| 30%   30C    P2              57W / 450W |   1574MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090        Off | 00000000:13:00.0 Off |                  Off |
| 30%   33C    P2              52W / 450W |  18572MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |

应该是模型刚加载完，还没开始跑，看上面的报错，是不是我这边在处理 prompt 的时候有些问题？麻烦您有空了再帮忙分析分析。

**Comment by wikeeyang** [comment]
大佬好！在2张4090上没跑成功，但我在自己笔记本+外置显卡 24GB 上倒是跑成功了，按您的思路，把 text_encoder 加载到 CPU，其它加载到 24GB 显卡，速度也还行，能跑出结果来。多谢多谢！

making attention of type 'causual_spatial_temporal' with 512 in_channels
making attention of type 'causual_spatial_temporal' with 512 in_channels
vae load from ./pretrain_model/vidgen/vae/vae_pytorch_model.bin
_IncompatibleKeys(missing_keys=[], unexpected_keys=['loss.logvar', 'loss.perceptual_loss.scaling_layer.shift', 'loss.perceptual_loss.scaling_layer.scale', 'loss.perceptual_loss.net.slice1.0.weight', 'loss.perceptual_loss.net.slice1.0.bias', 'loss.perceptual_loss.net.slice1.2.weight', 'loss.perceptual_loss.net.slice1.2.bias', 'loss.perceptual_loss.net.slice2.5.weight', 'loss.perceptual_loss.net.slice2.5.bias', 'loss.perceptual_loss.net.slice2.7.weight', 'loss.perceptual_loss.net.slice2.7.bias', 'loss.perceptual_loss.net.slice3.10.weight', 'loss.perceptual_loss.net.slice3.10.bias', 'loss.perceptual_loss.net.slice3.12.weight', 'loss.perceptual_loss.net.slice3.12.bias', 'loss.perceptual_loss.net.slice3.14.weight', 'loss.perceptual_loss.net.slice3.14.bias', 'loss.perceptual_loss.net.slice4.17.weight', 'loss.perceptual_loss.net.slice4.17.bias', 'loss.perceptual_loss.net.slice4.19.weight', 'loss.perceptual_loss.net.slice4.19.bias', 'loss.perceptual_loss.net.slice4.21.weight', 'loss.perceptual_loss.net.slice4.21.bias', 'loss.perceptual_loss.net.slice5.24.weight', 'loss.perceptual_loss.net.slice5.24.bias', 'loss.perceptual_loss.net.slice5.26.weight', 'loss.perceptual_loss.net.slice5.26.bias', 'loss.perceptual_loss.net.slice5.28.weight', 'loss.perceptual_loss.net.slice5.28.bias', 'loss.perceptual_loss.lin0.model.1.weight', 'loss.perceptual_loss.lin1.model.1.weight', 'loss.perceptual_loss.lin2.model.1.weight', 'loss.perceptual_loss.lin3.model.1.weight', 'loss.perceptual_loss.lin4.model.1.weight'])
pretrain_model/vidgen/text_encoder\t5-v1_1-xxl
Loading checkpoint shards: 100%|████████████████████████████| 2/2 [02:03<00:00, 61.57s/it]
model load from: pretrain_model/vidgen/transformer/diffusion_pytorch_model.bin
<All keys matched successfully>
  0%|                                                                                         | 0/50 [00:00<?, ?it/s]C:\AITest\VidGen\python310\lib\site-packages\torch\utils\checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
C:\AITest\VidGen\python310\lib\site-packages\torch\utils\checkpoint.py:90: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
100%|█████████████████████████████████████| 50/50 [05:33<00:00,  6.67s/it]
video_recons: torch.Size([1, 3, 34, 512, 512])
write to: sample_result/sampling_iddpm_50_512x512_video_t-34_seed41/t2v_0.gif
write to: sample_result/sampling_iddpm_50_512x512_video_t-34_seed41/t2v_0.mp4
prompt: In the video, a person is seen drawing a character on a white sheet of paper. The artist uses a black pen to sketch the character, starting with the head and then moving on to the body. The character appears to be a young man with short hair, wearing a long-sleeved shirt. The artist pays close attention to the details, such as the folds in the shirt and the contours of the face. The drawing is done in a realistic style, with careful attention to shading and proportion. The artist's hand is steady, and the pen moves confidently across the paper, suggesting that they are experienced in drawing. The video captures the creation of the character from start to finish, providing a glimpse into the artist's process and technique.

两张 4090 是在 Ubuntu 上，可能环境有些不同，去再看看代码，再尝试尝试。。。😜

**Comment by CanvaChen** [comment]
是的，只改两个文件。现在报错问题解决了吗？我猜测是cuda版本太低了，建议11.8或者12.1。

**Comment by wikeeyang** [comment]
感谢大佬！有可能，我 Ubuntu 上装了 12.4 和 11.8，虚拟环境我用了 11.8，改天换成 12.4 试试。😊，主要是跑出来之后，看了看，这个 VidGen 视频质量很一般，比 CodVideoX 还差，就没太多兴趣再去折腾了。。。况且，复旦原作那班人，好像丢点东西出来就跟完成任务似的。。。丢出来就十天八天不看一眼了。。。😂

**Comment by CanvaChen** [comment]
折腾这些是项目需要还是自己随便玩玩呢？

**Comment by wikeeyang** [comment]
算早期调研吧，也有一定的想法，但目前开源的项目都不太成熟，商用的目前起步成本都比较高。😂
